
name: Simple Node.JS Workflow with Docker

on:
  push:
    branches:
      - main

jobs:
    build:
    
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        
        - name: Build the Docker image
          run: docker build -t my-node-app .

        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Tag the Docker image
          run: docker tag my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app

        - name: Push the Docker image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app

        